apiVersion: v1
kind: Service
metadata:
  name: yarp-proxy
  namespace: yarp
spec:
  ports:
    - name: proxy
      port: 80
      protocol: TCP
      targetPort: 8000
    - name: proxy-ssl
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: gateway-yarp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-yarp
  name: yarp-proxy
  namespace: yarp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-yarp
  template:
    metadata:
      labels:
        app: gateway-yarp
    spec:
      containers:
        - name: yarp-proxy
          imagePullPolicy: IfNotPresent
          image: gateway-proxy
          ports:
            - containerPort: 8000
              name: proxy
              protocol: TCP
            - containerPort: 8443
              name: proxy-ssl
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://*:8000
---